char *eventString[] = {
	"waiting for childbirth",
	"I am born",
	"waiting for abortion",
	"chose termination",
	"last user finished",
	"killing a child",
	"waiting for children to die",
	"last child dying",
	"I\'m exiting",
	"I\'m dying, you shouldn't be waiting",
	"I\'m aborting you",
	"eating a late timer signal",
	"eating a late transaction signal",
	"eating a late termination signal",
	"serve me",
	"waiting on a transaction",
	"waiting for a possible timeout",
	"tcall time out",
	"accept waiting",
	"select waiting",
	"delaying",
	"accepting a client",
	"treturn",
	"I got a return",
	"debugger ending"
};
