#define CHANNEL 5
#define LINESpERpROCESS 2
#define CLOCKrOW 3
#define CLOCKcOL 55

#define COLS		85
#define LINES		64

#define USEReRRlINES	3+1
#define USERiolINES	10+1
#define CDBeRRlINES 	2+1
#define CONTROLlINES	3+1

#define CDBlINES	LINES-(USEReRRlINES+USERiolINES+CDBeRRlINES+CONTROLlINES)

#define USEReRRsTART	1
#define USERiosTART	USEReRRsTART+USEReRRlINES
#define CONTROLsTART	USERiosTART+USERiolINES
#define CDBeRRsTART	CONTROLsTART+CONTROLlINES
#define CDBsTART	CDBeRRsTART+CDBeRRlINES
