#define accept(id)	DD_Info->specTable->accept[id]
#define create(id)	DD_Info->specTable->create[id]
#define transact(id)	DD_Info->specTable->transact[id]
#define select(id)	DD_Info->specTable->select[id]
#define delay(id)	DD_Info->specTable->delay[id]
#define terminate(id)	DD_Info->specTable->terminate[id]
#define treturn(id)	DD_Info->specTable->treturn[id]
